# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b0744a31766cc333c5d491514ef3fac780a6f951ba6765e498edd368d29c192f863c62a8c783808dcb968818a366857822c32add4ef331c335f75c038e4b0895

test:
  secret_key_base: b74b5593a6596292d4b6586f2fcea643d3f37c6225cb2f1de163034d5ba28363f3c83d563b01867ab21877e42ef9b40e973eaa84e82aa26c0ea88b43d683e086

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
